### ISSUE TITLE
Memory leak in ComObject::Construct

### ISSUE THREAD

**Issue by TobBrandt-Work** [SlimDX/slimdx#504] opened 2016-03-17 11:18 UTC
Line 138 in ComObject.cpp uses `QueryInterface`:

`HRESULT hr = unknown->QueryInterface( Utilities::ConvertManagedGuid( guid ), &result );`

According to the [documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682521%28v=vs.85%29.aspx), this calls `AddRef` on the returned pointer (`result`). Therefore, you must call `Release` or a memory leak will occur.

**Comment by jpetrie** [comment] 2016-03-25 21:38
Apparently I still had notifications enabled for this project despite having stepped down from active development on it years ago.

Anyway, I'm fairly certain there's no leak here. The implicit `AddRef` done by the QI is what we expect to keep the COM object alive while SlimDX is using it. The returned pointer, which has a reference count of one (from SlimDX's perspective) is stored in the object table and used for the duration of the lifetime of the SlimDX wrapper object. When we `Release` this pointer, we're saying SlimDX is done with it. It's not done with it until the `ComObject` is destroyed, at which point we `Destruct` (line 145) and handle the `Release` there. We only skip the release when the object has the ancillary flag set, which is only done manually.

On the other hand, if the QI fails, `AddRef` isn't called ("This method calls `IUnknown::AddRef` *on the pointer it returns*," emphasis mine), so the only scenario that matters is when the QI passes.

**Comment by Promit** [comment] 2016-03-26 02:49
Yep, the implied AddRef is the intended behavior - you'll find that it calls ObjectTable::Add, so that represents our reference to the supplied object. This particular constructor allows us to absorb externally supplied objects into SlimDX and have everything behave seamlessly. 

And yes, this was every bit as painful to get right as it sounds.

**Comment by TobBrandt-Work** [comment] 2016-03-29 09:21
> SlimDX tries to ensure it only has a single outstanding reference count to any given COM object at a time

I noticed that. It makes it a bit inconvenient to use the API because you never know for sure whether you have to dispose an object returned from one of the `FromPointer` methods or not. For example:

    IntPtr somePtr = ...
    var obj1 = Resource.FromPointer(somePtr);
    var obj2 = Resource.FromPointer(somePtr);
  
Depending on where `somePtr` came from, I now need to either dispose exactly one of `obj1` and `obj2` (whichever lives longer) or none, but never both.

Anyway, that's a different issue.

> When we `Release` this pointer, we're saying SlimDX is done with it. It's not done with it until the `ComObject` is destroyed, at which point we `Destruct` (line 145) and handle the `Release` there.

That is true and it will work _most_ of the time. Unfortunately, `Destruct` calls `Release` on the original `IUnknown` pointer which is not necessarily the same pointer as the one returned by `QueryInterface`. A COM object is allowed to keep separate reference counts per interface in order to implement a [tear-off interface](https://msdn.microsoft.com/en-us/library/h9f7kdd8.aspx).

I don't know whether this facility is used in Direct X and I haven't observed a memory leak yet, but it's at least a possibility.

**Comment by jpetrie** [comment] 2016-03-29 15:19
You are correct that there are scenarios where this maintain-one-reference-count creates awkward ownership issues. The corresponding use of the `IDisposable` interface is also problematic, as it's semantics don't really line up with the way we tried to leverage the interface for reference counting. It was a design mistake.

D3D has never been a particularly well-behaved COM citizen, several of its interfaces weren't actually COM objects at all. None of the ones that were, to my knowledge, _ever_ returned differing pointers in the way you're describing.

**Comment by Promit** [comment] 2016-03-30 20:57
The integration with COM was always terribly awkward. The design fixed one set of problems that was on our minds at the time, but introduced another set. It is definitely a design peculiar to DX and how we interact with it, and would not hold up as a general purpose implementation.

**Closed** 2016-07-18 15:46 UTC
